apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-svc
  namespace: {{ .Release.Namespace | default .Values.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}-backend
  annotations:
    prometheus.io/port: "{{ .Values.backend.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-backend