apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-svc
  namespace: {{ .Release.Namespace | default .Values.namespace | default "default" }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-frontend