apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-jaeger-collector
  namespace: {{ .Release.Namespace | default .Values.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}-jaeger
spec:
  selector:
    app: {{ .Chart.Name }}-jaeger
  ports:
  - port: 14268
    targetPort: 14268
    name: collector
    nodePort: 30084
  - port: 16686
    targetPort: 16686
    name: query
    nodePort: 30085
  type: NodePort 